### ISSUE TITLE
Metrics for Prometheus doesn't work when using Vert.x launcher

### ISSUE THREAD

**Issue by jt-aztech** [vertx-howtos/metrics-prometheus-grafana-howto#2]
Tested this using: Vert.x 4.5.1 or 4.4.0

While trying to add prometheus metrics to a vert'x application the metrics doesn't work when using Vert.x launcher.

Steps to reproduce

    Download the project here: https://how-to.vertx.io/metrics-prometheus-grafana-howto/
    Run it normally and the metrics is exposed here: http://localhost:8080/metrics
    No setup vert.x Launcher and run the project again and when you go to: http://localhost:8080/metrics you get a response of http code 500 with message: Invalid registry: null

Tested this on ubuntu Ubuntu 20.04.6 LTS with java 17(see attached screenshot of vert.x launcher configurations).

![Screenshot from 2024-01-13 20-01-44](https://github.com/vertx-howtos/metrics-prometheus-grafana-howto/assets/156491732/2732fffb-5b58-47b6-b008-e80a3881c894)

**Comment by tsegismont** [comment]
Metrics are disabled by default. The `MainVerticle` in this how-to has its own `main` method which enables metrics and prometheus.

If you want to use the `Launcher` you need something like `--options='{"metricsOptions":{"enabled":true,"prometheusOptions":{"enabled":true}}}'`

**Comment by jt-aztech** [comment]
that is the whole point, it doesn't work. You could've just said that on the original ticket.

**Comment by tsegismont** [comment]
We try to track issues (of all sorts: questions, bug reports, ...etc) in the most appropriate repository. As opensource maintainers, this helps us keeping a clear view of the problems in their different categories.

I spent some time reproducing the scenario you described before I understood the problem. Sometimes bug reports are just a wrong usage. Sometimes questions actually reveal a bug. To make a decision, we need to take some time. We often don't make this effort before the issue is logged in the proper repository.

Perhaps you thought all solutions are immediately apparent to us, and thus you didn't understand why I didn't answer immediately. Perhaps you know nothing about maintaining an opensource project. Perhaps, it's both. In any case, you shouldn't feel entitled to make such comments.

**Comment by jt-aztech** [comment]
You are somewhat correct on both accounts, anyway, thanks for your efforts
